config/routes.rb
PlanesDeNegocio::Application.routes.draw do
  resources :questions

  get "session/new"

  get "session/destroy"

  get "/search" => "home#search"
  post "/search" => "home#find_results"

  resources :business_planes

  resources :entrepreneurs

  root  :to => "home#index"

end

app/models/business_plane.rb
class BusinessPlane < ActiveRecord::Base
  attr_accessible :acknowledgment, :category, :duration, :gross_margin, :roi, :title, :total_investment, :vision
  validates :acknowledgment, :category, :duration, :gross_margin, :roi, :title, :total_investment, :vision, :presence => true

  belongs_to :entrepreneur

  CATEGORIES = ["World Peace", "Tech", "IT", "Education (urgently needed)"]

  def self.search(title)
    BusinessPlane.where("title like ?", "%#{title}%")
  end

end

app/models/entrepreneur.rb
class Entrepreneur < ActiveRecord::Base
  attr_accessible :address, :born_at, :cellphone, :document_number, :document_type, :email, :first_name, :gender, :last_name, :password
  validates :address, :born_at, :cellphone, :document_number, :document_type, :email, :first_name, :gender, :last_name, :password, :presence => true

  validates :email, :document_number, :uniqueness => true

  DOCUMENT_TYPES = {:dni => "DNI", :passport => "Pasaporte"}

  has_many :business_planes

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :business_plane_id, :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/business_planes_controller.rb
class BusinessPlanesController < ApplicationController
  # GET /business_planes
  # GET /business_planes.json
  def index
    @business_planes = BusinessPlane.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @business_planes }
    end
  end

  # GET /business_planes/1
  # GET /business_planes/1.json
  def show
    @business_plane = BusinessPlane.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @business_plane }
    end
  end

  # GET /business_planes/new
  # GET /business_planes/new.json
  def new
    @business_plane = BusinessPlane.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @business_plane }
    end
  end

  # GET /business_planes/1/edit
  def edit
    @business_plane = BusinessPlane.find(params[:id])
  end

  # POST /business_planes
  # POST /business_planes.json
  def create
    @business_plane = BusinessPlane.new(params[:business_plane])

    respond_to do |format|
      if @business_plane.save
        format.html { redirect_to @business_plane, notice: 'Business plane was successfully created.' }
        format.json { render json: @business_plane, status: :created, location: @business_plane }
      else
        format.html { render action: "new" }
        format.json { render json: @business_plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /business_planes/1
  # PUT /business_planes/1.json
  def update
    @business_plane = BusinessPlane.find(params[:id])

    respond_to do |format|
      if @business_plane.update_attributes(params[:business_plane])
        format.html { redirect_to @business_plane, notice: 'Business plane was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business_plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_planes/1
  # DELETE /business_planes/1.json
  def destroy
    @business_plane = BusinessPlane.find(params[:id])
    @business_plane.destroy

    respond_to do |format|
      format.html { redirect_to business_planes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/entrepreneurs_controller.rb
class EntrepreneursController < ApplicationController
  # GET /entrepreneurs
  # GET /entrepreneurs.json
  def index
    @entrepreneurs = Entrepreneur.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entrepreneurs }
    end
  end

  # GET /entrepreneurs/1
  # GET /entrepreneurs/1.json
  def show
    @entrepreneur = Entrepreneur.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entrepreneur }
    end
  end

  # GET /entrepreneurs/new
  # GET /entrepreneurs/new.json
  def new
    @entrepreneur = Entrepreneur.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entrepreneur }
    end
  end

  # GET /entrepreneurs/1/edit
  def edit
    @entrepreneur = Entrepreneur.find(params[:id])
  end

  # POST /entrepreneurs
  # POST /entrepreneurs.json
  def create
    @entrepreneur = Entrepreneur.new(params[:entrepreneur])

    respond_to do |format|
      if @entrepreneur.save
        format.html { redirect_to @entrepreneur, notice: 'Entrepreneur was successfully created.' }
        format.json { render json: @entrepreneur, status: :created, location: @entrepreneur }
      else
        format.html { render action: "new" }
        format.json { render json: @entrepreneur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entrepreneurs/1
  # PUT /entrepreneurs/1.json
  def update
    @entrepreneur = Entrepreneur.find(params[:id])

    respond_to do |format|
      if @entrepreneur.update_attributes(params[:entrepreneur])
        format.html { redirect_to @entrepreneur, notice: 'Entrepreneur was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entrepreneur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entrepreneurs/1
  # DELETE /entrepreneurs/1.json
  def destroy
    @entrepreneur = Entrepreneur.find(params[:id])
    @entrepreneur.destroy

    respond_to do |format|
      format.html { redirect_to entrepreneurs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end

  def search
    
  end

  def find_results
    @search = params[:title]
    @results = BusinessPlane.search(@search)
    render :search
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_planes_helper.rb
module BusinessPlanesHelper
end

app/helpers/entrepreneurs_helper.rb
module EntrepreneursHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/business_planes/_form.html.erb
<%= simple_form_for(@business_plane) do |f| %>
  <% if @business_plane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business_plane.errors.count, "error") %> prohibited this business_plane from being saved:</h2>

      <ul>
      <% @business_plane.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.association :entrepreneur, :label_method => "first_name" %>
  </div>
  

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.input :category, :collection => BusinessPlane::CATEGORIES %>
  </div>
  <div class="field">
    <%= f.label :vision %><br />
    <%= f.text_area :vision %>
  </div>
  <div class="field">
    <%= f.label :acknowledgment %><br />
    <%= f.text_area :acknowledgment %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :total_investment %><br />
    <%= f.text_field :total_investment %>
  </div>
  <div class="field">
    <%= f.label :gross_margin %><br />
    <%= f.text_field :gross_margin %>
  </div>
  <div class="field">
    <%= f.label :roi %><br />
    <%= f.text_field :roi %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/business_planes/edit.html.erb
<h1>Editing business_plane</h1>

<%= render 'form' %>

<%= link_to 'Show', @business_plane %> |
<%= link_to 'Back', business_planes_path %>

app/views/business_planes/index.html.erb
<h1>Listing business_planes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Category</th>
    <th>Vision</th>
    <th>Acknowledgment</th>
    <th>Duration</th>
    <th>Total investment</th>
    <th>Gross margin</th>
    <th>Roi</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @business_planes.each do |business_plane| %>
  <tr>
    <td><%= business_plane.title %></td>
    <td><%= business_plane.category %></td>
    <td><%= business_plane.vision %></td>
    <td><%= business_plane.acknowledgment %></td>
    <td><%= business_plane.duration %></td>
    <td><%= business_plane.total_investment %></td>
    <td><%= business_plane.gross_margin %></td>
    <td><%= business_plane.roi %></td>
    <td><%= link_to 'Show', business_plane %></td>
    <td><%= link_to 'Edit', edit_business_plane_path(business_plane) %></td>
    <td><%= link_to 'Destroy', business_plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Business plane', new_business_plane_path %>

app/views/business_planes/new.html.erb
<h1>New business_plane</h1>

<%= render 'form' %>

<%= link_to 'Back', business_planes_path %>

app/views/business_planes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @business_plane.title %>
</p>

<p>
  <b>Category:</b>
  <%= @business_plane.category %>
</p>

<p>
  <b>Vision:</b>
  <%= @business_plane.vision %>
</p>

<p>
  <b>Acknowledgment:</b>
  <%= @business_plane.acknowledgment %>
</p>

<p>
  <b>Duration:</b>
  <%= @business_plane.duration %>
</p>

<p>
  <b>Total investment:</b>
  <%= @business_plane.total_investment %>
</p>

<p>
  <b>Gross margin:</b>
  <%= @business_plane.gross_margin %>
</p>

<p>
  <b>Roi:</b>
  <%= @business_plane.roi %>
</p>


<%= link_to 'Edit', edit_business_plane_path(@business_plane) %> |
<%= link_to 'Back', business_planes_path %>

app/views/entrepreneurs/_form.html.erb
<%= simple_form_for(@entrepreneur) do |f| %>
  <% if @entrepreneur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entrepreneur.errors.count, "error") %> prohibited this entrepreneur from being saved:</h2>

      <ul>
      <% @entrepreneur.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.input :gender, :collection => ["Male", "Female"] %>
  </div>
  <div class="field">
    <%= f.input :document_type, :collection => Entrepreneur::DOCUMENT_TYPES.values %>
  </div>
  <div class="field">
    <%= f.label :document_number %><br />
    <%= f.text_field :document_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cellphone %><br />
    <%= f.text_field :cellphone %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :born_at %><br />
    <%= f.datetime_select :born_at %>
  </div>
  <div class="field">
    <%= f.input :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entrepreneurs/edit.html.erb
<h1>Editing entrepreneur</h1>

<%= render 'form' %>

<%= link_to 'Show', @entrepreneur %> |
<%= link_to 'Back', entrepreneurs_path %>

app/views/entrepreneurs/index.html.erb
<h1>Listing entrepreneurs</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Gender</th>
    <th>Document type</th>
    <th>Document number</th>
    <th>Email</th>
    <th>Cellphone</th>
    <th>Address</th>
    <th>Born at</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entrepreneurs.each do |entrepreneur| %>
  <tr>
    <td><%= entrepreneur.first_name %></td>
    <td><%= entrepreneur.last_name %></td>
    <td><%= entrepreneur.gender %></td>
    <td><%= entrepreneur.document_type %></td>
    <td><%= entrepreneur.document_number %></td>
    <td><%= entrepreneur.email %></td>
    <td><%= entrepreneur.cellphone %></td>
    <td><%= entrepreneur.address %></td>
    <td><%= entrepreneur.born_at %></td>
    <td><%= entrepreneur.password %></td>
    <td><%= link_to 'Show', entrepreneur %></td>
    <td><%= link_to 'Edit', edit_entrepreneur_path(entrepreneur) %></td>
    <td><%= link_to 'Destroy', entrepreneur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entrepreneur', new_entrepreneur_path %>

app/views/entrepreneurs/new.html.erb
<h1>New entrepreneur</h1>

<%= render 'form' %>

<%= link_to 'Back', entrepreneurs_path %>

app/views/entrepreneurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @entrepreneur.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @entrepreneur.last_name %>
</p>

<p>
  <b>Gender:</b>
  <%= @entrepreneur.gender %>
</p>

<p>
  <b>Document type:</b>
  <%= @entrepreneur.document_type %>
</p>

<p>
  <b>Document number:</b>
  <%= @entrepreneur.document_number %>
</p>

<p>
  <b>Email:</b>
  <%= @entrepreneur.email %>
</p>

<p>
  <b>Cellphone:</b>
  <%= @entrepreneur.cellphone %>
</p>

<p>
  <b>Address:</b>
  <%= @entrepreneur.address %>
</p>

<p>
  <b>Born at:</b>
  <%= @entrepreneur.born_at %>
</p>

<p>
  <b>Password:</b>
  <%= @entrepreneur.password %>
</p>


<%= link_to 'Edit', edit_entrepreneur_path(@entrepreneur) %> |
<%= link_to 'Back', entrepreneurs_path %>

app/views/home/search.html.erb
<h1>Searching business plans</h1>

<%= form_tag "/search" do %>
    <%= text_field_tag "title" %>
    <%= submit_tag "Buscar" %>
<% end %>

<%- if @results %>
<table>
  <tr>
    <th>Title</th>
    <th>Category</th>
    <th>Vision</th>
    <th>Acknowledgment</th>
    <th>Duration</th>
    <th>Total investment</th>
    <th>Gross margin</th>
    <th>Roi</th>
    <th></th>
  </tr>

<% @results.each do |business_plane| %>
  <tr>
    <td><%= business_plane.title %></td>
    <td><%= business_plane.category %></td>
    <td><%= business_plane.vision %></td>
    <td><%= business_plane.acknowledgment %></td>
    <td><%= business_plane.duration %></td>
    <td><%= business_plane.total_investment %></td>
    <td><%= business_plane.gross_margin %></td>
    <td><%= business_plane.roi %></td>
    <td><%= link_to 'Show', business_plane %></td>
  </tr>
<% end %>
</table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlanesDeNegocio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=ABeeZee' rel='stylesheet' type='text/css'>

</head>
<body>
<h1 class="title">Built in 13 minutes</h1>
<%= link_to "Registrar Emprendedor/Sabio", new_entrepreneur_path %>
<%= link_to "Emprendedores", entrepreneurs_path %>
<%= link_to "Registrar Plan de Negocio", new_business_plane_path %>
<%= link_to "Planes de Negocio", business_planes_path %>
<%= link_to "Buscar Plan de Negocios", "/search" %>


<%= yield %>

</body>
</html>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<h1>Session#new</h1>
<p>Find me in app/views/session/new.html.erb</p>